const DIFFICULTIES = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD',
  BASIC: 'BASIC',
  CONCEPTUAL: 'CONCEPTUAL',
  GATE_LEVEL: 'GATE_LEVEL',
  ADVANCED: 'ADVANCED',
};

module.exports = {
  DIFFICULTIES,
  VALID_DIFFICULTIES: Object.values(DIFFICULTIES),
};
