const TOPIC_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  LEARNING: 'LEARNING',
  PRACTICE: 'PRACTICE',
  PYQ_COMPLETED: 'PYQ_COMPLETED',
  COMPLETED: 'COMPLETED',
  WEAK: 'WEAK',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
};

const TOPIC_THRESHOLDS = {
  COMPLETION_ACCURACY: 80, // >= 80% marks topic COMPLETED
  REVISION_ACCURACY: 60,   // 60-79% COMPLETED + Revision Recommended
  WEAK_ACCURACY: 60,       // < 60% marked as WEAK
  MIN_MCQS_FOR_TOPIC: 10,  // Each topic requires 10 MCQs
};

module.exports = {
  TOPIC_STATUS,
  TOPIC_THRESHOLDS,
};
